name: Publish to Comfy Registry

on:
  push:
    branches:
      - main
    paths:
      - "pyproject.toml"
  workflow_dispatch:

jobs:
  publish-node:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Publish node
        uses: Comfy-Org/publish-node-action@main
        with:
          personal_access_token: ${{ secrets.REGISTRY_ACCESS_TOKEN }}

